Controllers/PaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Session05ArchitectureMVC.Models;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Session05ArchitectureMVC.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly Keys keys;

        public PaymentController(IConfiguration configuration)
        {
            this.configuration = configuration;
            string pubKey = configuration["Stripe:PublishableKey"];
            keys = new Keys {
                amount = 500,
                currency = "aud",
                description = "Sample",
                publicKey = pubKey
            };
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(keys);
        }

        // This is the action method that the form in the Payment/Index view
        // posts to.
        [AllowAnonymous]
        public IActionResult Charge(string stripeEmail, string stripeToken)
        {
            // Workaround because key is not persisting from Startup.cs
            string secretKey = configuration.GetValue<string>("Stripe:SecretKey");
            StripeConfiguration.ApiKey = secretKey;

            var customers = new CustomerService();
            var charges = new ChargeService();

            // Pass email and token to CustomerService.Create() .
            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = stripeEmail,
                Source = stripeToken
            });

            var charge = charges.Create(new ChargeCreateOptions
            {
                Amount = keys.amount,
                Description = keys.description,
                Currency = keys.currency,
                CustomerId = customer.Id
            });

            return View();
        }

        [AllowAnonymous]
        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/PostController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Session05ArchitectureMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Session05ArchitectureMVC.Controllers
{
    public class PostController : Controller
    {
        List<Post> p;
        private readonly TableDataContext _db;

        public PostController(TableDataContext db)
        {
            _db = db;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [Route("p")] // this allows the URL to be shortened to simply ./p
        public IActionResult ShowPost(int id)
        {
            return new ContentResult { Content = "My post controller (ShowPost method), post ID: " + id };
        }

        [Route("{year}/{month}/{key}")] // you can specify multiple arguments in the route
        public IActionResult ShowDate(int year, int month, string key)
        {
            return new ContentResult { Content = "Year: " + year + ", Month: " + month + ", Key: " + key };
        }

        public IActionResult Display()
        {
            // Check to see if the user is signed in. If not, redirect to the 
            // Login view in Account controller.
            var strUserId = HttpContext.Session.GetString("userId");

            if( strUserId == null )
            {
                return RedirectToAction("Login", "Account");
            }
            
            // Session [""]
            /*
            HttpContext.Session.SetString("userID", "MyValueOrObject");
            int x = 0;
            */
            
            // Display all the Post objects.
            /*
            p = _db.post.ToList<Post>();

            return View(p);
            */

            // Alternatively, the query can be made using LINQ.
            //var p1 = from v in _db.post select v;

            // LINQ can also be used to modify entries as they are retrieved:
            /*
            var p1 = from v1 in _db.post
                     join v2 in _db.department
                     on v1.Id equals v2.postId
                     select new
                     {
                         Id1 = v1.Id,
                         newsContent1 = v1.title + " (" + v2.deptName + ")",
                         publishedOn1 = v1.publishedOn,
                         publishedBy1 = v1.publishedBy
                     };

            List<Post> p3 = new List<Post>();
            foreach(var p2 in p1)
            {
                p3.Add(new Post
                    {
                        Id = p2.Id1,
                        newsContent = p2.newsContent1,
                        publishedOn = p2.publishedOn1,
                        publishedBy = p2.publishedBy1
                    }
                ); ;
            }
            */

            var p1 = from v1 in _db.post
                     join v2 in _db.department
                     on v1.Id equals v2.postId into eGroup
                     from v2 in eGroup.DefaultIfEmpty()

                     select new
                     {
                         Id1 = v1.Id,
                         newsContent1 = v1.title + " (" + v2.deptName + ")",
                         publishedOn1 = v1.publishedOn,
                         publishedBy1 = v1.publishedBy
                     };

            List<Post> p3 = new List<Post>();
            foreach (var p2 in p1)
            {
                p3.Add(new Post
                {
                    Id = p2.Id1,
                    newsContent = p2.newsContent1,
                    publishedOn = p2.publishedOn1,
                    publishedBy = p2.publishedBy1
                }
                ); ;
            }

            return View(p3.ToList<Post>());
        }

        // Adding a keyword to assign an action method to a specific HTTP request
        [HttpGet]
        public IActionResult Add()
        {
            // Create a new Post object with the current timestamp prefilled.
            Post p = new Post { publishedOn = DateTime.Now };

            return View(p);
        }

        [HttpPost]
        public IActionResult Add(Post p2)
        {
            // Ensure fields are valid before posting.
            if(!ModelState.IsValid)
            {
                return View();
            }
            
            // Add the new post to the post table and save changes.
            _db.post.Add(p2);
            _db.SaveChanges();

            return RedirectToAction("Display");
        }

        [HttpGet]
        public IActionResult Edit(long Id)
        {
            // Find the corresponding post entry in the database.
            Post p = _db.post.Find(Id);

            // Return the view with the post information.
            return View(p);

            // Alternatively, the same can be achieved with LINQ.
            var p1 = from v in _db.post where v.Id == Id select v;
            
            // Return the first result.
            return View(p1.FirstOrDefault<Post>());
        }

        [HttpPost]
        public IActionResult Edit(Post p)
        {
            // Ensure fields are valid.
            if (!ModelState.IsValid)
            {
                return View();
            }

            var p1 = from v in _db.post where v.Id == p.Id select v;
            List<Post> list = p1.ToList<Post>();

            foreach(Post p4 in list)
            {
                p4.title += " (Updated)";
                _db.Entry(p4).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _db.SaveChanges();
            }

            // Inform Entity Framework that the data for this entry has been modified.
            /*
            _db.Entry(p).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _db.SaveChanges();
            */

            return RedirectToAction("Display");
        }

        [HttpGet]
        public IActionResult Delete(long Id)
        {
            // Find the post by Id, then remove the post and save changes.
            Post p = _db.post.Find(Id);
            _db.post.Remove(p);

            _db.SaveChanges();

            return RedirectToAction("Display");
        }
    }
}

Views/Shared/_DisplayPostPartial.cshtml
@* Do not use view start or layout in a partial view *@
@model Session05ArchitectureMVC.Models.Post
<div>
    @Html.DisplayFor(m => m.Id)
    <img src="~/images/myflower.jpg" />
</div>

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device-width, initial-scale=1" />

    <!-- Include bootstrap CSS and JS (can be dragged from solution explorer). -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <title>Project Name</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Project Name</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <!-- ActionLink takes the following arguments: link text, action method, controller, routevalues (here null), can add attributes -->
                        <li class="nav-item">
                            @Html.ActionLink("Add Page", "Add", "Post",
                                new { title = "Go to the add page." },
                                new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Display Page", "Display", "Post",
                                new { title = "Go to the display page." },
                                new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Stripe Payment Example", "Index", "Payment",
                                new { title = "Visit the Stripe payment example page." },
                                new { @class = "nav-link" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            <!-- RenderBody() is used to place the view within the template -->
            @RenderBody()
        </div>
    </main>
    <footer class="bg-light">
        <div class="container">
            <small>This is the footer.</small>
        </div>
    </footer>
</body>
</html>